### ISSUE TITLE
Update README.md for release v2.0

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#123]

**Comment by x448** [comment]
Standards section:

__EncOptions.Time__:  

* TimeUnix: (seconds) encode time as integer.
* TimeUnixMicro: (microseconds) encoded to floating-point using ShortestFloat option.
* TimeUnixDynamic: (seconds or microseconds) encode time as integer if time doesn't have fractional seconds, otherwise encode to floating-point rounded to microseconds.
* TimeRFC3339: (seconds) encode as RFC 3339 formatted string.
* TimeRFC3339Nano: (nanoseconds) causes time to be encoded as RFC3339 formatted string.

By default, time values are encoded without tags.  Option to override this will be added in v2.1.

**Comment by x448** [comment]
Default settings for these and other options need to be made obvious in the README.
