### ISSUE TITLE
feature: Add option to ignore omitempty flag of tag

### ISSUE THREAD

**Issue by jkralik** [fxamacker/cbor#202]
**Is your feature request related to a problem? Please describe.**
For protobufs that are generated by protoc, it is harcod-ed tag for json. If I serialized protobuf struct to CBOR I want to add default values but it is not added because omitempty tag.

**Describe the solution you'd like**
Implement option that alllow's you ignore omitempty flag.

**Comment by x448** [comment]
@fxamacker I think this request is to ignore json:"omitempty" because it is always generated by protoc.  A workaround is to use sed to remove variations of omitempty in a script that calls protoc.

@jkralik if protoc is willing to add a command-line option to not generate omitempty tags, would that be good enough to close this issue?  I think that would be the cleanest solution.

BTW, the "toarray" struct tag automatically disables "omitempty" for all fields that struct.

**Comment by fxamacker** [comment]
@jkralik It seems that protobuf project closed an issue related to `protoc` and "omitempty" without considering non-JSON libraries encoding the generated structs.

> protoc-gen-go + omitempty JSON struct tags
> https://github.com/golang/protobuf/issues/799

Instead, `protoc` shifted this problem to `jsonpb` to deal with unwanted "omitempty" being generated by `protoc`.

> jsonpb package Marshaler.EmitDefaults (Whether to render fields with zero values.)
> https://godoc.org/github.com/golang/protobuf/jsonpb#Marshaler

__Workaround__
protobuf issue 52 has comments that mention tools for adding custom tags -- I think you can probably use it to add CBOR struct tag which would override JSON struct tag for the same field.

https://github.com/golang/protobuf/issues/52

If `protoc` never adds the option to not generate unwanted "omitempty", I'm inclined to agree with @x448 about using a wrapper script to remove "omitempty" (or add CBOR struct tag using tools mentioned in protobuf issue 52).

Please let me know if this works for you.

**Comment by jkralik** [comment]
OK . It will be works for me. Thx

**Comment by amitbhave10** [comment]
@fxamacker , is there any alternative/official solution for the same?
As there is also not any official solution for: https://github.com/golang/protobuf/issues/52
