### ISSUE TITLE
Properly handle empty values for custom types

### ISSUE THREAD

**Issue by kostko** [fxamacker/cbor#232]
Currently using `omitempty` with custom types doesn't work correctly due to [it being hardcoded](https://github.com/fxamacker/cbor/blob/bffaf0cda7c548af6e819cd5385f025bb6fee6f8/encode.go#L1329-L1345). For example, empty structs are still encoded as empty maps instead of omitting the field and fields for types implementing `encoding.BinaryMarshaler` are still included even when `MarshalBinary` returns an empty `[]byte`.

It seems that the `isEmptyValue` was copied from `encoding/json` but it behaving this way really makes it harder to support more compact encodings.

It would be great if one could override empty value handling for custom types or if existing empty value handling would behave correctly at least for the above two cases (empty structs and types implementing `encoding.BinaryMarshaler`).

**Comment by fxamacker** [comment]
Thanks for reporting this.  I'll look into it.

**Comment by fxamacker** [comment]
@kostko  commit 58b1cf4afc2b9bbab0f5bb4ac1977000e0a25435 adds support for omitting empty structs and types implementing encoding.BinaryMarshaler.

https://play.golang.com/p/uiEjJmJpSEG

https://play.golang.com/p/4XvWHzih3PE

Although this isn't an official release, commit 58b1cf4afc2b9bbab0f5bb4ac1977000e0a25435 has passed fuzzing since yesterday (335 million execs and counting).

Please let me know if it works for you.

**Comment by kostko** [comment]
Thanks for the fix, will take a look!
