### ISSUE TITLE
feature: pretty printer

### ISSUE THREAD

**Issue by kaihendry** [fxamacker/cbor#310]
**Is your feature request related to a problem? Please describe.**
i have a random cbor, but i don't know how to inspect its structure / generate struct tags

**Describe the solution you'd like**
some example of how to pretty print it 

**Describe alternatives you've considered**
https://www.npmjs.com/package/cbor-pretty-print

**Comment by fxamacker** [comment]
Hi Kai, if the CBOR data isn't confidential then you might want to consider online alternatives like:
* [cbor.me](https://cbor.me) --  appears to be registered to Carsten Bormann (author of CBOR RFC) and allows file upload
* [geraintluff.github.io/cbor-debug/](https://geraintluff.github.io/cbor-debug/)

I think using my library to create a CBOR pretty printer would be overkill.  But a Go alternative to the npm package you mentioned would be nice since some prefer not to install npm due to security concerns.  Please let me know if you come across a good alternative.
