### ISSUE TITLE
docs: tag release v2.3.1 without any coding changes to allow 3rd-party sites to display updated docs

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#311]
### What is the URL of the content?

README.md

### Please describe the problem.

The README for v2.3.0 (May 30, 2021) has a  typo in example code that can cause problems.

README was updated but some 3rd-party sites won't show the corrections until a new release is tagged.

### Suggestion

Tag release v2.3.1 without coding changes.  

Fuzzing won't have to be rerun.  It shouldn't take up much time to do.  I don't see any downsides.

**Comment by fxamacker** [comment]
@x448 I think some extra lint checking was done after v2.3.0.  I'd prefer to keep those lint msg cleanups and run fuzz test if we decide to release a v2.3.1.

This would have to wait at least until next weekend.  My cold should go away in a few days since it has been about a week.  Maybe it makes more sense to release v2.4.0 during the holidays with 2-3 requested features that don't have workarounds.

**Comment by fxamacker** [comment]
v2.3.1 will be tagged today.   Fuzzing for 2.4.0 was started yesterday.

I'll push v2.4.0 changes to GitHub after tagging v2.3.1.
