### ISSUE TITLE
feature: increase 256 limit for MaxNestedLevels to allow decoding data with larger nesting levels

### ISSUE THREAD

**Issue by immesys** [fxamacker/cbor#354]
### What version of fxamacker/cbor are you using?

v.2.4.0

### Does this issue reproduce with the latest release?

Yes

I have a data structure encoded with serde_cbor from Rust. It's a sparse tree-like object that is a known, but large depth (about 600 levels). I completely understand the rationale behind MaxNestedLevels, and the default being 32 seems sane to me. But why, if I am going out of my way to pick a higher maximum in my decoding options, am I limited to 256 as the max? It means I can't decode this known-good, signed data structure. What was the original rationale behind this particular number for the limit?

It's also a limit that is seemingly not common in other cbor libraries which can prevent interoperability. Can we remove/increase this maximum and instead put a sentence in the documentation about why you may want to think twice before setting it to a large number?

### What did you expect to see?

No limit on MaxNestedLevels unless there was a technological limitation or other hard-limit reason for it

### What did you see instead?

A limit that, for me, is inconveniently low.

**Comment by immesys** [comment]
I will also note that our initial attempts to resolve this by doing lazy decoding using cbor.RawMessage failed because RawMessage does not seem to prevent the invocation of `decoder.validInternal`

**Comment by fxamacker** [comment]
> I completely understand the rationale behind MaxNestedLevels, and the default being 32 seems sane to me. But why, if I am going out of my way to pick a higher maximum in my decoding options, am I limited to 256 as the max?

@immesys Thanks for opening this issue and submitting the PR!  Your PR looks great and I'll merge it.

About 3 years ago, it was assumed by some (including me) that exceeding 255 levels would likely be an accident.

:warning:  Some other CBOR codecs will not be able to decode data exceeding 127 or 255 nested levels.  

Other CBOR codecs with hardcoded nesting level limits include:

- 255 limit (C):  [qcbor](https://github.com/laurencelundblade/QCBOR) is a CBOR codec by one of the reviewers to the draft RFC which became RFC 8949.

- 127 limit (Rust): [oasis_cbor](https://docs.rs/oasis-cbor) is currently the top search result on Google for: cbor max nested level. It's relatively new (just 1 year old).

BTW, I'm not 100% sure but I suspect 256 was initially intended to be 255 because I knew of qcbor and trust its author.  The intent was to not stray from other RFC draft reviewers and revisit the max allowed limit at some point. 

Thanks again for the PR!

**Comment by immesys** [comment]
Thanks for the rapid response. I made the changes you requested on the PR, but in light of your comment here, do you think I should add something to the doc that mentions that other libraries may be limited to 127 or 255 levels? I'm on the fence, because on one side, that may be useful information that the developer may be interested in, but on the other side it's an Unmarshal-time check not a Marshal-time check, so there's no guarantee that if I am marshalling an object using this library, intending it to be unmarshalled by someone else using a different library, that I would ever read the doc for MaxNestedLevels or see any runtime error

**Comment by fxamacker** [comment]
> Thanks for the rapid response. I made the changes you requested on the PR, but in light of your comment here, do you think I should add something to the doc that mentions that other libraries may be limited to 127 or 255 levels? I'm on the fence, because on one side, that may be useful information that the developer may be interested in, but on the other side it's an Unmarshal-time check not a Marshal-time check, so there's no guarantee that if I am marshalling an object using this library, intending it to be unmarshalled by someone else using a different library, that I would ever read the doc for MaxNestedLevels or see any runtime error

Good point!   I think given this limit is an "Unmarshal-time check" as you said, adding a comment about the limits of other codecs can be skipped.

When time allows, I'll add a section to the README about interoperability with other codecs and include several considerations such as this one.

**Comment by fxamacker** [comment]
This is closed by PR #355 contributed by @immesys.  Great work and thank you!  👍
