### ISSUE TITLE
bug: Unmarshal and Valid should check following extraneous data

### ISSUE THREAD

**Issue by zensh** [fxamacker/cbor#359]
### What version of fxamacker/cbor are you using?
v2.4.0

### Does this issue reproduce with the latest release?
Yes

### What OS and CPU architecture are you using (`go env`)?
MacOS, m1
<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?

```go
data := []byte{0, 1, 2, 3}
err := cbor.Valid(data) // should return a error

var val interface{}
err = cbor.Unmarshal(data, &val) // should return a error
```

**Comment by fxamacker** [comment]
@zensh Thank you for reporting this!

`Unmarshal()` and `Valid` work this way to be compatible with decoder, which can continue decoding extra data.  But I understand your point because `Unmarshal()` and `Valid()` only decodes one piece of data.

Rejecting extraneous data would be a breaking change.  So maybe it can be added as a non-default `DecOption`.  This new option would only apply for `Unmarshal()` and `Valid()`.  Thoughts?

**Comment by fxamacker** [comment]
@zensh Thanks again for raising this issue!

After rereading relevant sections in RFC 8949 and comparing to how this is handled in `encoding/json`, I changed this from enhancement to a bug.

It makes more sense to return extraneous data error by default when calling `Unmarshal()` and `Valid()`.  This way, the change would not modify API signature and it would be a bug fix to be more consistent with RFC 8949 and also handle this like `encoding/json` package.

Would you like to update PR #359 or would you like me to open a new PR?
