### ISSUE TITLE
Wrap error returned from MarshalCBOR in MarshalerError

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#486]
Currently, error returned from `MarshalCBOR()` are returned from codec as is, without being wrapped.

PR #485 adds `MarshalerError`, which wraps error from well-formedness check for CBOR data item returned from `MarshalCBOR()`.  

However, error returned directly from `MarshalCBOR()` should also be wrapped in `MarshalerError` to be consistent with Go's `encoding/json` package.

Resolving this would be a breaking change due to different type of error being returned which only affects error handling of `Marshaler`.

**Comment by fxamacker** [comment]
Maybe this bugfix can be justified as part of larger PR #485 but I don't like changes that might be breaking changes for some.

@benluddy what are your thoughts on this specific bugfix and this type of bugfix in general?  We currently follow SemVer with some limited exceptions noted in README.

**Comment by benluddy** [comment]
I agree with the desired behavior but wouldn't make the breaking change. Users who differentiate error handling behaviors based on specific errors from a cbor.Marshaler are exactly the same users that would potentially be broken by wrapping the error, and other users would only see marginal benefit.

Instead of making this change and trying to communicate it loudly to users, WDYT about addressing this as part of a new marshaler interface (https://github.com/fxamacker/cbor/pull/485#pullrequestreview-1863056406)?

**Comment by fxamacker** [comment]
> Instead of making this change and trying to communicate it loudly to users, WDYT about addressing this as part of a new marshaler interface (https://github.com/fxamacker/cbor/pull/485#pullrequestreview-1863056406)?

@benluddy Thanks, I opened issue to add new interface as alternative to `Marshaler`:
- #507

The new interface can address limitations of `Marshaler` discussed here and also discussed for proposed `encoding/json/v2` at
- https://github.com/golang/go/discussions/63397
